sudo : required 
services:
  - docker

before_install:
  - docker build -t abbashusainy/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  -docker build -t abbashusainy/multi-client ./client
  -docker build -t abbashusainy/multi-nginx ./nginx
  -docker build -t abbashusainy/multi-server ./server
  -docker build -t abbashusainy/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  - docker push abbashusainy/multi_client
  - docker push abbashusainy/multi-nginx
  - docker push abbashusainy/multi-server 
  - docker push abbashusainy/multi-work